version: '3.7'
services:
  profiles:
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: dockermysql:3306
    depends_on:
      - dockermysql
    networks:
      - backend
    volumes:
      - images-data:/data
      - ./sql:/docker-entrypoint-initdb.d
  dockermysql:
    restart: always
    container_name: dockermysql
    image: mysql
    environment:
      MYSQL_DATABASE: profiles
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  db-data:
  images-data:
networks:
  backend:
